# Generated by Django 4.0.3 on 2022-04-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='document',
            field=models.FileField(null=True, upload_to='portfolio/images/'),
        ),
    ]
